### ISSUE TITLE
design an application form

### ISSUE THREAD

**Issue by lsetiawan** [oceanhackweek/administrative#7]
- [x] read Daniela Huppenkothen's post on [participant selection](https://danielahuppenkothen.wordpress.com/2016/11/16/workshop-participant-selection-from-start-to-finish-an-example/)
- [x] choose a survey platform. We recommend Google forms or jotform (which allows for users to attach files, e.g. a CV)
- [x] design the application form. Consult with prior hackweek organizers regarding how best to design applications that maximize diversity and minimize potential for bias. See examples from [geo](https://form.jotform.com/geohack/2018)  and [neuro](https://form.jotform.com/80126067304145) hackweeks.
Note that we have formatted the application to contain categorical inputs so that these responses can be input into the [Entrofy algorithm](https://github.com/dhuppenkothen/entrofy) we use to assist in applicant selection.

**Comment by aaarendt** [comment]
Geohack form is here: https://form.jotform.com/geohack/2018

**Comment by leewujung** [comment]
@friedrichknuth -- can you draft an application form with inputs from @amanda-tan and @lsetiawan ?
We will then have a conf call later this week to settle this

**Comment by friedrichknuth** [comment]
@aaarendt @lsetiawan I recall the application form being a very carefully constructed document for multiple reasons, including alignment with the participant contribution weighting algorithm. is there a template we can draw from to start with?

**Comment by aaarendt** [comment]
@friedrichknuth see the third checkbox in the first post of this issue...there are hyperlinks to the geo and neuro application forms. There you'll see we have some slightly different approaches. I'm happy to discuss the various pros/cons of different was of setting up questions.

**Comment by friedrichknuth** [comment]
woops... rtm... thanks!!

**Comment by friedrichknuth** [comment]
link to draft below. 

https://www.jotform.com/build/80724479940162?iak=70caff9b054ee03f6b64415c7d0b79c6-e78845468726d149

**Comment by leewujung** [comment]
Final form: https://form.jotform.com/oceanhack/2018
